package_name: fraud_detection_model

# data
train_data_file: train.csv
valid_data_file: valid.csv

# variable
target: Class

pipeline_name: fraud_detection_model
pipeline_save_file: fraud_detection_model_output_v

features:
  - Time
  - V1
  - V2
  - V3
  - V4
  - V5
  - V6
  - V7
  - V8
  - V9
  - V10
  - V11
  - V12
  - V13
  - V14
  - V15
  - V16
  - V17
  - V18
  - V19
  - V20
  - V21
  - V22
  - V23
  - V24
  - V25
  - V26
  - V27
  - V28
  - Amount

# train/test split
test_size: 0.3

# random seed
random_state: 0

# sampling_strategy
sampling_strategy: 0.1
